package com.ecommerce.motomart.Models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "payments")
public class Payment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentId;

    @OneToOne
    @JoinColumn(name = "order_id")
    private Order order;

    @ManyToOne // Assuming a payment can be linked to one user
    @JoinColumn(name = "user_id") // Create a foreign key in the payments table
    private User user;

    private Double amount;
    private Date paymentDate;
    private String paymentMethod;
    private String paymentStatus; // New field to track the status of the payment

    // Getters and Setters (automatically generated by Lombok)
}
