package com.ecommerce.motomart.DTO;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class PaymentDTO {
    private Long paymentId; // Updated name to match entity field
    private Long orderId; // Assuming payment is linked to an order
    private Long userId; // New field to track the user associated with the payment
    private Double amount;
    private Date paymentDate;
    private String paymentMethod; // New field for payment method
    private String paymentStatus; // New field for payment status

    // Getters and Setters (automatically generated by Lombok)
}
